

const routes = {
  home: '/',
  profile: '/profile',
  login: '/login',
  register: '/register',
  verify: '/verify',
  changePassword: '/change-password',
  forgotPassword: '/forgot-password',
  completeGoogleProfile: '/CompleteGoogleProfile',
  shop: '/shop/:id',
  contact: '/contact/',
  cart: '/cart/',
  testimonial: '/testimonial',
  product: '/product/:id',
  customerManagement: '/customer',
  dashboard: '/dashboard',
   dashboardSupplier: '/dashboard-supplier',
  addProduct: '/addproduct',
  listProduct: '/listproduct',
  orderList: '/orderlist',
  userList: '/userlist',
  requestUpgradeRole: '/request-upgrade-role',
  checkout: '/checkout',
  requestProduct: '/requestProduct',
  purchase: '/purchase',
  feedback: '/reviews',
  orders: '/orders',
  shipperList: '/shipperlist',
  customerList: '/customerlist',
  supplierList: '/supplierlist',
  productSearch: '/products/search',
  ordersPending: '/orders/pending',
  redeemVoucher: '/redeem-voucher',
  acceptUpdateRole: '/acceptupdaterole',
  orderDetail: '/order-detail/:id',
  orderDetailCustomer: '/order-information/:id',
  chat : '/chat/:conversationId',
};

export default routes;